// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: rpc/rusprofile.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Rusprofile_Get_FullMethodName = "/Rusprofile/Get"
)

// RusprofileClient is the client API for Rusprofile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RusprofileClient interface {
	Get(ctx context.Context, in *InnRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
}

type rusprofileClient struct {
	cc grpc.ClientConnInterface
}

func NewRusprofileClient(cc grpc.ClientConnInterface) RusprofileClient {
	return &rusprofileClient{cc}
}

func (c *rusprofileClient) Get(ctx context.Context, in *InnRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	out := new(ProfileResponse)
	err := c.cc.Invoke(ctx, Rusprofile_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RusprofileServer is the server API for Rusprofile service.
// All implementations must embed UnimplementedRusprofileServer
// for forward compatibility
type RusprofileServer interface {
	Get(context.Context, *InnRequest) (*ProfileResponse, error)
	mustEmbedUnimplementedRusprofileServer()
}

// UnimplementedRusprofileServer must be embedded to have forward compatible implementations.
type UnimplementedRusprofileServer struct {
}

func (UnimplementedRusprofileServer) Get(context.Context, *InnRequest) (*ProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRusprofileServer) mustEmbedUnimplementedRusprofileServer() {}

// UnsafeRusprofileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RusprofileServer will
// result in compilation errors.
type UnsafeRusprofileServer interface {
	mustEmbedUnimplementedRusprofileServer()
}

func RegisterRusprofileServer(s grpc.ServiceRegistrar, srv RusprofileServer) {
	s.RegisterService(&Rusprofile_ServiceDesc, srv)
}

func _Rusprofile_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RusprofileServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rusprofile_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RusprofileServer).Get(ctx, req.(*InnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rusprofile_ServiceDesc is the grpc.ServiceDesc for Rusprofile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rusprofile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Rusprofile",
	HandlerType: (*RusprofileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Rusprofile_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/rusprofile.proto",
}
